import React from 'react';

interface Props { onClose: () => void; }

export default function TermsOfService({ onClose }: Props) {
  return (
    <div className="fixed inset-0 z-[200] bg-[#FAF7F2] overflow-y-auto">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <button onClick={onClose} className="mb-8 flex items-center gap-2 text-[#0F1B2D]/50 hover:text-[#0F1B2D] transition-colors text-sm font-medium">
          ← Back to ChaptersBook.com
        </button>
        <h1 className="font-display text-4xl font-bold text-[#0F1B2D] mb-2">Terms of Service</h1>
        <p className="text-sm text-[#0F1B2D]/50 mb-10">Last updated: May 2025 · ChaptersBook.com</p>

        {[
          {
            title: "1. Acceptance of Terms",
            body: `By accessing or using ChaptersBook.com ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.`
          },
          {
            title: "2. Description of Service",
            body: `ChaptersBook.com is an AI-powered platform that helps users create personalized story books. We offer solo and group book creation modes, AI-assisted writing, editing tools, and downloadable book outputs in various formats.`
          },
          {
            title: "3. Account Registration",
            body: `To access certain features, you must create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must provide accurate and complete information and keep your account information updated.`
          },
          {
            title: "4. Payments & Subscriptions",
            body: `Free accounts may create and preview books at no cost. Downloading finished books requires a paid plan (Standard at $19/book or Premium at $39/book) or an active subscription. All payments are processed securely via Stripe. Prices are in USD and subject to change with notice.\n\n30-Day Money-Back Guarantee: If you are not satisfied with your downloaded book, contact us within 30 days of purchase for a full refund.`
          },
          {
            title: "5. Intellectual Property & Content Ownership",
            body: `You retain full ownership of the story content you submit and the books generated from your content. By submitting content, you grant ChaptersBook.com a limited, non-exclusive license to process and display your content solely for the purpose of generating your book.\n\nChaptersBook.com retains ownership of the platform, its underlying technology, and all AI models. You may not reverse-engineer, copy, or resell the platform or its outputs for commercial redistribution.`
          },
          {
            title: "6. Acceptable Use",
            body: `You agree not to: (a) submit content that is illegal, harmful, defamatory, or infringes on third-party rights; (b) use the Service to generate content that sexualizes minors; (c) attempt to circumvent payment systems; (d) use automated scripts to access the Service without permission; (e) impersonate other persons or entities.`
          },
          {
            title: "7. AI-Generated Content Disclaimer",
            body: `Books generated by ChaptersBook.com are created using AI based on your inputs. While we strive for quality and accuracy, we do not guarantee that AI-generated content will be error-free, factually accurate, or meet all your expectations. You are responsible for reviewing and editing your book before publication or distribution.`
          },
          {
            title: "8. Group Books",
            body: `When you create a group book and invite contributors, you are responsible for ensuring all contributors have consented to participate and to our Terms. You are the "book owner" and have control over the final output. Contributors are not liable for the final published book.`
          },
          {
            title: "9. Limitation of Liability",
            body: `To the maximum extent permitted by law, ChaptersBook.com shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits or data. Our total liability to you for any claim shall not exceed the amount you paid us in the 12 months preceding the claim.`
          },
          {
            title: "10. Termination",
            body: `We may suspend or terminate your account for violation of these Terms. You may cancel your account at any time by contacting support@chaptersbook.com. Upon termination, your right to access the Service ceases, but your downloaded books remain yours.`
          },
          {
            title: "11. Governing Law",
            body: `These Terms shall be governed by the laws of the State of Delaware, United States, without regard to conflict of law principles. Any disputes shall be resolved in the courts of Delaware.`
          },
          {
            title: "12. Changes to Terms",
            body: `We reserve the right to modify these Terms at any time. We will notify users of material changes via email or site notice. Continued use of the Service after changes constitutes acceptance.`
          },
          {
            title: "13. Contact",
            body: `For questions about these Terms, contact us at:\n\nChaptersBook.com\nEmail: legal@chaptersbook.com`
          }
        ].map(({ title, body }) => (
          <div key={title} className="mb-8">
            <h2 className="font-display text-xl font-semibold text-[#0F1B2D] mb-3">{title}</h2>
            <p className="text-[#0F1B2D]/70 leading-relaxed whitespace-pre-line">{body}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
